### ISSUE TITLE
Broken Code

### ISSUE THREAD

**Issue by pra-dan** [Rishit-dagli/Smart-Queuing-System-On-Edge#4]
Hey, I think you should check your code once again. I noticed some discrepencies in it. For eg, You never used `preprocess_outputs` in your code. People trusting you may waste days ... Look here: https://knowledge.udacity.com/questions/254540

He is using your code and needs help. Kindly Look into it

**Comment by Rishit-dagli** [comment]
I have once again verified the code and it works for me. Be sure to read the docs. Also if you are still facing the issue, send me a screenshot and I would be happy to look into it.

> https://knowledge.udacity.com/questions/254540

This post nowhere mentions using my code. You should reconsider your claims. I am closing this issue as of now, you are welcome to add comments to this if it remains unsolved.
